version: "3.9"

services:
  laravel:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
      - ./backend/vendor:/var/www/html/vendor
    ports:
      - 8000:8000
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: secret
    depends_on:
      - db
    networks:
      - app-network
    command: >
      sh -c "
        # Install dependencies if vendor folder missing
        [ ! -d vendor ] && composer install;

        # Copy .env if missing and generate app key
        [ ! -f .env ] && cp .env.example .env;
        php artisan key:generate;

        # Run migrations and seed database
        php artisan migrate:fresh --seed;

        # Start Laravel server
        php artisan serve --host=0.0.0.0 --port=8000
      "

  nextjs:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nextjs_app
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      NEXT_PUBLIC_API_URL: "http://localhost:8000/api/v1"
    depends_on:
      - laravel
    networks:
      - app-network
    command: >
      sh -c "
        npm install --silent;
        npm run dev
      "

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
