version: "3.9"

services:
  laravel:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www/html
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: secret
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        [ ! -f .env ] && cp .env.example .env && echo ".env file copied successfully"
        composer install
        php artisan key:generate
        php artisan migrate:fresh --seed
        php artisan serve --host=0.0.0.0 --port=8000
    volumes:
      - ./backend:/var/www/html
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  nextjs:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: "http://localhost:8000/api/v1"
    container_name: nextjs_app
    restart: unless-stopped
    ports:
      - 3000:3000
    depends_on:
      - laravel
    networks:
      - app-network

  db:
    image: mysql:8.4
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - 3306:3306
    volumes:
      - app_mysql_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "laravel",
          "-psecret",
        ]
      interval: 5s
      timeout: 3s
      retries: 5

networks:
  app-network:
    driver: bridge

volumes:
  app_mysql_data:
